version: "3.8"
services:
  devcontainer:
    build: .
    image: dotnet:7
    container_name: dotnet7-dev

    tty: true
    stdin_open: true

    volumes:
      - ./app:/workspaces

    working_dir: /workspaces

    command: /bin/bash
    # command: dotnet run