version: "3.8"
services:
  devcontainer:
    build: .
    image: dotnet:7
    container_name: dotnet7-dev

    volumes:
      - ./app:/workspaces

    working_dir: /workspaces

    command: dotnet run